<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>GDB Session</string>
    <key>repository</key>
    <dict>
        <key>string_escaped_char</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(\\|[abefnprtv'"?]|[0-3]\d{0,2}|[4-7]\d?|x[a-fA-F0-9]{0,2}|u[a-fA-F0-9]{0,4}|U[a-fA-F0-9]{0,8})</string>
                    <key>name</key>
                    <string>constant.character.escape.c</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>invalid.illegal.unknown-escape.c</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^([0-9]+)(-\S+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.gdb.command</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>

        <dict>
            <key>match</key>
            <string>^~.*$</string>
            <key>name</key>
            <string>comment</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^([0-9]+)(\^[^,]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.other.gdb.command</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.gdb.returncode</string>
                </dict>
            </dict>
        </dict>

        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.gdb</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.gdb</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.gdb</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#string_escaped_char</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>[^{,=]+(?==)</string>
            <key>name</key>
            <string>storage.type.gdb</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.gdb.session</string>
    <key>uuid</key>
    <string>36F30C2C-0443-4944-9FA4-3940126FD71A</string>
</dict>
</plist>
